# Default Config.yml

# The main game settings (this goes for all arenas):
waiting_time: 30
total_game_time: 120
scoreboard_enable: true
names_on_board_max: 5
exp_time_enable: true
give_snowballs_on_start:
  enable: true
  amount: 10

# If it hits a certain time, an event will happen in seconds.
# Info on what you can do:
# snowballs: give the player a certain amount of snowballs.
# speed: make them go very fast for a duration of time (in seconds)
# slow: Slow them down a little bit of time (in seconds).
# jump: Make them jump a little higher for a duration of time (in seconds)
# tntfall: Make tnt rain upon the players (only drops once for
# the amount of players already in the arena, for best results, type 2.
# Amplification (amp) is only for potion effects.
enable_time_events: true
time_events:
  90:
    jump: 8
    amp: 8
  60:
    snowballs: 20
  45:
    slow: 3
    amp: 5
  30:
    snowballs: 30
  10:
    tntfall: 2
  5:
    speed: 4
    amp: 5

# Blocks given to players (Not the display name, but the actual block).
setup_wizard_blocks:
  cancel: "barrier"
  maximum: "magenta_wool"
  minimum: "lime_wool"
  spectator: "white_wool"
  lobby: "red_wool"
  arena: "light_blue_wool"
  complete: "sunflower"
edit_wizard_blocks:
  name: "paper"
  maximum: "magenta_wool"
  minimum: "lime_wool"
  spectator: "white_wool"
  lobby: "red_wool"
  arena: "light_blue_wool"
  complete: "sunflower"
in_lobby:
  leave: "barrier"